export const MAP_SELECTED = "MAP_SELECTED"

export const GET_MAPS_REQUEST = "GET_MAPS_REQUEST"
export const GET_MAPS_REQUEST_SUCCESS = "GET_MAPS_REQUEST_SUCCESS"
export const GET_MAPS_REQUEST_ERROR = "GET_MAPS_REQUEST_ERROR"

export const ADD_MAP_REQUEST = "ADD_MAP_REQUEST"
export const ADD_MAP_REQUEST_SUCCESS = "ADD_MAP_REQUEST_SUCCESS"
export const ADD_MAP_REQUEST_ERROR = "ADD_MAP_REQUEST_ERROR"

export const UPDATE_MAP_REQUEST = "UPDATE_MAP_REQUEST"
export const UPDATE_MAP_REQUEST_SUCCESS = "UPDATE_MAP_REQUEST_SUCCESS"
export const UPDATE_MAP_REQUEST_ERROR = "UPDATE_MAP_REQUEST_ERROR"

export const ADD_POINT_REQUEST = "ADD_POINT_REQUEST"
export const ADD_POINT_REQUEST_SUCCESS = "ADD_POINT_REQUEST_SUCCESS"
export const ADD_POINT_REQUEST_ERROR = "ADD_POINT_REQUEST_ERROR"

export const GET_GROUP_REQUEST = "GET_GROUP_REQUEST"
export const GET_GROUP_REQUEST_SUCCESS = "GET_GROUP_REQUEST_SUCCESS"
export const GET_GROUP_REQUEST_ERROR = "GET_GROUP_REQUEST_ERROR"

export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST"
export const ADD_GROUP_REQUEST_SUCCESS = "ADD_GROUP_REQUEST_SUCCESS"
export const ADD_GROUP_REQUEST_ERROR = "ADD_GROUP_REQUEST_ERROR"

export const ADD_FILTER_REQUEST = "ADD_FILTER_REQUEST"
export const ADD_FILTER_REQUEST_SUCCESS = "ADD_FILTER_REQUEST_SUCCESS"
export const ADD_FILTER_REQUEST_ERROR = "ADD_FILTER_REQUEST_ERROR"

export const UPDATE_GROUP_REQUEST = "UPDATE_GROUP_REQUEST"
export const UPDATE_GROUP_REQUEST_SUCCESS = "UPDATE_GROUP_REQUEST_SUCCESS"
export const UPDATE_GROUP_REQUEST_ERROR = "UPDATE_GROUP_REQUEST_ERROR"

export const UPDATE_FILTER_REQUEST = "UPDATE_FILTER_REQUEST"
export const UPDATE_FILTER_REQUEST_SUCCESS = "UPDATE_FILTER_REQUEST_SUCCESS"
export const UPDATE_FILTER_REQUEST_ERROR = "UPDATE_FILTER_REQUEST_ERROR"

export const GET_FILTER_POINTS_REQUEST = "GET_FILTER_POINTS_REQUEST"
export const GET_FILTER_POINTS_REQUEST_SUCCESS = "GET_FILTER_POINTS_REQUEST_SUCCESS"
export const GET_FILTER_POINTS_REQUEST_ERROR = "GET_FILTER_POINTS_REQUEST_ERROR"

export const ADD_FILTER_POINTS_REQUEST = "ADD_FILTER_POINTS_REQUEST"
export const ADD_FILTER_POINTS_REQUEST_SUCCESS = "ADD_FILTER_POINTS_REQUEST_SUCCESS"
export const ADD_FILTER_POINTS_REQUEST_ERROR = "ADD_FILTER_POINTS_REQUEST_ERROR"

export const DELETE_MAP_REQUEST = "DELETE_MAP_REQUEST"
export const DELETE_MAP_REQUEST_SUCCESS = "DELETE_MAP_REQUEST_SUCCESS"
export const DELETE_MAP_REQUEST_ERROR = "DELETE_MAP_REQUEST_ERROR"

export const DELETE_MAP_GROUP_REQUEST = "DELETE_MAP_GROUP_REQUEST"
export const DELETE_MAP_GROUP_REQUEST_SUCCESS = "DELETE_MAP_GROUP_REQUEST_SUCCESS"
export const DELETE_MAP_GROUP_REQUEST_ERROR = "DELETE_MAP_GROUP_REQUEST_ERROR"

export const DELETE_GROUP_FILTER_REQUEST = "DELETE_GROUP_FILTER_REQUEST"
export const DELETE_GROUP_FILTER_REQUEST_SUCCESS = "DELETE_GROUP_FILTER_REQUEST_SUCCESS"
export const DELETE_GROUP_FILTER_REQUEST_ERROR = "DELETE_GROUP_FILTER_REQUEST_ERROR"

export const DELETE_FILTER_POINTS_REQUEST = "DELETE_FILTER_POINTS_REQUEST"
export const DELETE_FILTER_POINTS_REQUEST_SUCCESS = "DELETE_FILTER_POINTS_REQUEST_SUCCESS"
export const DELETE_FILTER_POINTS_REQUEST_ERROR = "DELETE_FILTER_POINTS_REQUEST_ERROR"

export const DELETE_FILTER_POINT_REQUEST = "DELETE_FILTER_POINT_REQUEST"
export const DELETE_FILTER_POINT_REQUEST_SUCCESS = "DELETE_FILTER_POINT_REQUEST_SUCCESS"
export const DELETE_FILTER_POINT_REQUEST_ERROR = "DELETE_FILTER_POINT_REQUEST_ERROR"

export const UPDATE_FILTER_POINTS_REQUEST = "UPDATE_FILTER_POINTS_REQUEST"
export const UPDATE_FILTER_POINTS_REQUEST_SUCCESS = "UPDATE_FILTER_POINTS_REQUEST_SUCCESS"
export const UPDATE_FILTER_POINTS_REQUEST_ERROR = "UPDATE_FILTER_POINTS_REQUEST_ERROR"



